### ISSUE TITLE
[BUG] Words containing italic tags fails when trying to fetch definitions

### ISSUE THREAD

**Issue by josnih21** [account0123/RAE-API#5] opened 2022-02-25 17:53 UTC
Recently trying to consume from this API project, we found that searching for words that contain italic tags fails.

So what we're basically trying to do, following the current documentation is to: 

`rae.fetchWord(response.getRes()[0].getId()))`

What throws an error of **body.res is not iterable**

We try with Pizza and Paparazzi words and get the same result, the only reason we reach that this could be happening is related to the italic tags in the header word when trying to fetch the ID of the word.

**Comment by account0123** [comment] 2022-02-28 00:29
Thanks for reporting, i am just resolving the issue. If you ask what happened, it's because the API was confunding a json (word metadata) with an html paragraph (definition)

**Comment by account0123** [comment] 2022-02-28 05:09
I finally fixed the issue. The new version is 1.5.0 and it's working.

**Closed as completed by account0123** 2022-02-28 05:09 UTC

**Comment by josnih21** [comment] 2022-03-01 09:38
Thank you! @account0123

**Comment by gloaysa** [comment] 2023-03-09 18:03
The issue is again present in latest release 1.5.1, reverting back to 1.50 fixes it, just so you know.

I think the problem is in HttpInterface.js line 68. The Regex returns a null value and it still tries to access the index [1].

I tried with 'pizza' and 'jazz'

**Comment by lilezek** [comment] 2023-03-27 17:02
I can confirm this. For example, fetching the word becquerel crashes the API. Updating the code in the HttpInterface to parse the header like this fixes the issue:

```js
const h = body.match(/<header [^>]*>(<i>)?([^<]+)/)[2]
						.replace(/&#xE1;/g, 'á')
						.replace(/&#xE9;/g, 'é')
						.replace(/&#xED;/g, 'í')
						.replace(/&#xF3;/g, 'ó')
						.replace(/&#xFA;/g, 'ú')
						.replace(/&#xF1;/g, 'ñ');
```
